### ISSUE TITLE
Use soft-tabs with a two space indent

### ISSUE THREAD

**Issue by cignoir** [seconoid/awesome_events#1]
:relaxed: < FYI: http://bojovs.com/2012/04/24/ruby-coding-style/

**Comment by seconoid** [comment]
Wow :astonished: 　thanks comment :relaxed:
How did you check my code?

**Comment by cignoir** [comment]
You are under surveillance :eyes:
Keep it up :thumbsup:

**Comment by seconoid** [comment]
:eyes: :eyes: :eyes:
